name: CI

on:
  push:
    branches: ['master']
    tags-ignore: ['*']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/gulp.yml
    with:
      upload_artifacts: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master' }}
